/* Los íconos de Lucide que el kit puede dibujar; el resto queda fuera del
   bundle. Nació generado por la app de origen (los que ella usaba) y el molde le
   sumó los de sus piezas nuevas (globo, copiar, descargar, compartir). Cada app
   que necesite otro lo propone al molde: es una línea acá y otra abajo. */
import {
  Archive,
  ArrowDownLeft,
  ArrowDownUp,
  ArrowUpRight,
  Baseline,
  Bell,
  BellRing,
  Bold,
  Box,
  Calendar,
  CalendarClock,
  CalendarDays,
  CalendarX,
  ChartColumn,
  ChartLine,
  Check,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  ChevronsUpDown,
  Circle,
  CircleAlert,
  CircleHelp,
  ClipboardList,
  Clock,
  CornerDownRight,
  Currency,
  DoorOpen,
  Ellipsis,
  Eye,
  File,
  FileText,
  Focus,
  FolderHeart,
  Ghost,
  GripVertical,
  Group,
  History,
  House,
  IdCard,
  Info,
  LayoutGrid,
  List,
  Lock,
  LogOut,
  Mail,
  Megaphone,
  Menu,
  Mic,
  Moon,
  Mouse,
  Move,
  OctagonAlert,
  Option,
  Package,
  Paperclip,
  Pencil,
  Phone,
  Plus,
  Pointer,
  Presentation,
  Radio,
  Receipt,
  ReceiptText,
  RotateCcw,
  Rows3,
  Rows4,
  Scale,
  ScanBarcode,
  Scroll,
  Search,
  Section,
  Send,
  Settings,
  SlidersHorizontal,
  Snowflake,
  Sparkles,
  Square,
  Stethoscope,
  Sun,
  Text,
  Trash2,
  TrendingDown,
  TrendingUp,
  TriangleAlert,
  Truck,
  Underline,
  Users,
  Wallet,
  X,
  Copy,
  Download,
  Globe,
  Share2,
} from 'lucide-react';

export const ICONOS = {
  'archive': Archive,
  'arrow-down-left': ArrowDownLeft,
  'arrow-down-up': ArrowDownUp,
  'arrow-up-right': ArrowUpRight,
  'baseline': Baseline,
  'bell': Bell,
  'bell-ring': BellRing,
  'bold': Bold,
  'box': Box,
  'calendar': Calendar,
  'calendar-clock': CalendarClock,
  'calendar-days': CalendarDays,
  'calendar-x': CalendarX,
  'chart-column': ChartColumn,
  'chart-line': ChartLine,
  'check': Check,
  'chevron-down': ChevronDown,
  'chevron-left': ChevronLeft,
  'chevron-right': ChevronRight,
  'chevron-up': ChevronUp,
  'chevrons-up-down': ChevronsUpDown,
  'circle': Circle,
  'circle-alert': CircleAlert,
  'circle-help': CircleHelp,
  'clipboard-list': ClipboardList,
  'clock': Clock,
  'corner-down-right': CornerDownRight,
  'currency': Currency,
  'door-open': DoorOpen,
  'ellipsis': Ellipsis,
  'eye': Eye,
  'file': File,
  'file-text': FileText,
  'focus': Focus,
  'folder-heart': FolderHeart,
  'ghost': Ghost,
  'grip-vertical': GripVertical,
  'group': Group,
  'history': History,
  'house': House,
  'id-card': IdCard,
  'info': Info,
  'layout-grid': LayoutGrid,
  'list': List,
  'lock': Lock,
  'log-out': LogOut,
  'mail': Mail,
  'megaphone': Megaphone,
  'menu': Menu,
  'mic': Mic,
  'moon': Moon,
  'mouse': Mouse,
  'move': Move,
  'octagon-alert': OctagonAlert,
  'option': Option,
  'package': Package,
  'paperclip': Paperclip,
  'pencil': Pencil,
  'phone': Phone,
  'plus': Plus,
  'pointer': Pointer,
  'presentation': Presentation,
  'radio': Radio,
  'receipt': Receipt,
  'receipt-text': ReceiptText,
  'rotate-ccw': RotateCcw,
  'rows-3': Rows3,
  'rows-4': Rows4,
  'scale': Scale,
  'scan-barcode': ScanBarcode,
  'scroll': Scroll,
  'search': Search,
  'section': Section,
  'send': Send,
  'settings': Settings,
  'sliders-horizontal': SlidersHorizontal,
  'snowflake': Snowflake,
  'sparkles': Sparkles,
  'square': Square,
  'stethoscope': Stethoscope,
  'sun': Sun,
  'text': Text,
  'trash-2': Trash2,
  'trending-down': TrendingDown,
  'trending-up': TrendingUp,
  'triangle-alert': TriangleAlert,
  'truck': Truck,
  'underline': Underline,
  'users': Users,
  'wallet': Wallet,
  'x': X,
  'copy': Copy,
  'download': Download,
  'globe': Globe,
  'share-2': Share2,
};
